### ISSUE TITLE
RuntimeError UNETR

### ISSUE THREAD

**Issue by cogitas3d** [Maxlo24/CBCT_Seg#3]
Hey there!

I follow the documentation, install all packs on Ubuntu 20.04, and even running on different python versions, the error is the same.

The command:
python3 ~/Programs/AMASSS_CBCT-main/MULTI_SEG/src/predict_CBCTSeg.py -i ~/del/GRAVALOS/4_NII_GZ -o ~/del/GRAVALOS/4_NII_GZ_OUT/ -dm /home/xxx/Programs/AMASSS_CBCT-main/Models -ss MAND MAX CB CV UAW -vtk True

**ERROR Python3.7**

Loading model /home/xxx/Programs/AMASSS_CBCT-main/Models/seg_FF_model.pth
Traceback (most recent call last):
  File "/home/xxx/Programs/AMASSS_CBCT-main/MULTI_SEG/src/predict_CBCTSeg.py", line 498, in <module>
    main(args)
  File "/home/xxx/Programs/AMASSS_CBCT-main/MULTI_SEG/src/predict_CBCTSeg.py", line 371, in main
    net.load_state_dict(torch.load(model_path,map_location=DEVICE))
  File "/home/xxx/Programs/OrtogOnBlender/Blender291/2.91/python/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UNETR:
	Unexpected key(s) in state_dict: "vit.patch_embedding.cls_token", "encoder2.blocks.0.1.conv3.conv.weight", "encoder2.blocks.1.1.conv3.conv.weight", "encoder3.blocks.0.1.conv3.conv.weight". 
	
**ERROR Python 3.8**

Loading model /home/xxx/Programs/AMASSS_CBCT-main/Models/seg_FF_model.pth
Traceback (most recent call last):
  File "/home/xxx/Programs/AMASSS_CBCT-main/MULTI_SEG/src/predict_CBCTSeg.py", line 498, in <module>
    main(args)
  File "/home/xxx/Programs/AMASSS_CBCT-main/MULTI_SEG/src/predict_CBCTSeg.py", line 371, in main
    net.load_state_dict(torch.load(model_path,map_location=DEVICE))
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNETR:
	Unexpected key(s) in state_dict: "vit.patch_embedding.cls_token", "encoder2.blocks.0.1.conv3.conv.weight", "encoder2.blocks.1.1.conv3.conv.weight", "encoder3.blocks.0.1.conv3.conv.weight".

**Comment by Maxlo24** [comment]
Hello, I'm sorry I'm not the one taking care of that code now.
Try to ask on [https://github.com/DCBIA-OrthoLab/AMASSS_CBCT](https://github.com/DCBIA-OrthoLab/AMASSS_CBCT)

**Comment by cogitas3d** [comment]
I solved all problems and soon I hope share the solutions.

**Comment by cogitas3d** [comment]
Dear @Maxlo24

I was able to use the program on three different operating systems using the OrtogOnBlender addon.

Details are available in this draft (please, use Google translator): https://ortogonline.com/doc/pt_br/OrtogOnLineMag/8/AI.html

Thank you for the material you published that made all of this possible!

![AI_capa](https://github.com/Maxlo24/AMASSS_CBCT/assets/2422483/2774d843-29a1-40eb-961c-a12a0adea02c)
